### ISSUE TITLE
Video.mp4 result

### ISSUE THREAD

**Issue by HardysJin** [wshi999/733project#4]
![video](https://user-images.githubusercontent.com/33291963/165219269-e3bbc8f7-0171-4d22-a187-196eee61bfa7.gif)

Not sure if the output video is expected?

**Comment by wshi999** [comment]
No, this is not what I got. The result I got was linked in the report.

**Comment by wshi999** [comment]
https://drive.google.com/file/d/1_C0bfOQ1WckYOrjjR00qQTBMIW-GXxBh/view?usp=sharing
This was the result I got. I'm looking into it. Sorry for the confusion.

**Comment by wshi999** [comment]
The version you tested on is using the wrong output. I have made the change on my board. Sorry about that.
